sonar.projectKey=Gymkhana
sonar.projectName=Gymkhana
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=src/game/tests
sonar.test.inclusions=**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.ts,**/e2e/**,**/node_modules/**,**/dist/**,**/*.config.*,src/firebase/**,src/hooks/useOnlineGame.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/e2e/**,**/*.config.*,**/coverage/**

sonar.languages=ts
